# Файлы Python
__pycache__/
*.pyc
*.pyo
*.pyd
.Python

# Файлы venv
.venv/

# Файлы IDE
.idea/

# Докер
Dockerfile.web
Dockerfile.bot
docker-compose.yml
.dockerignore

# Git
.git
.gitignore
.gitkeep

# README
.md

# Bot
telegram_bot
run_bot.py
parser.py
bot.env

# Nginx
promapp