# Файлы Python
__pycache__/
*.pyc
*.pyo
*.pyd
.Python

# Файлы venv
.venv/

# Файлы IDE
.idea/

# Докер
Dockerfile.bot
Dockerfile.web
docker-compose.yml
.dockerignore

# Git
.git
.gitignore
.gitkeep

# README
.md

# Web
web_app
parser.py
web.env

# Nginx
promapp